#!/usr/bin/python2.4
# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2



_ECHOREQUEST = descriptor.Descriptor(
  name='EchoRequest',
  full_name='test.EchoRequest',
  filename='test.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='text', full_name='test.EchoRequest.text', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_ECHORESPONSE = descriptor.Descriptor(
  name='EchoResponse',
  full_name='test.EchoResponse',
  filename='test.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='text', full_name='test.EchoResponse.text', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)



class EchoRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ECHOREQUEST

class EchoResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ECHORESPONSE


_TEST = descriptor.ServiceDescriptor(
  name='Test',
  full_name='test.Test',
  index=0,
  options=None,
  methods=[
  descriptor.MethodDescriptor(
    name='Echo',
    full_name='test.Test.Echo',
    index=0,
    containing_service=None,
    input_type=_ECHOREQUEST,
    output_type=_ECHORESPONSE,
    options=None,
  ),
])

class Test(service.Service):
  __metaclass__ = service_reflection.GeneratedServiceType
  DESCRIPTOR = _TEST
class Test_Stub(Test):
  __metaclass__ = service_reflection.GeneratedServiceStubType
  DESCRIPTOR = _TEST

